---
# will be superseded by `flask' key after loading acc to user switches
modes:
    local:  #< default one
        ENV: development
        DEBUG: True
        TESTING: True
        SECRET_KEY: 'S0m3R3ally53cre757r1ng'
        SERVER_NAME: localhost.localdomain:5000
        # ... see: http://flask.pocoo.org/docs/1.0/config/
# Content paths
# ...
# Modules and their configurations, as array of objects. Will be loaded
# in order.
#
# Note, that the module name shall then be used as an initial prefix for
# loading JavaScript modules (via the require.js).
# Static path will be then received from blueprint object that has to be
# defined at `pyModule' module as a global variable `bp'.
modules:
    - name: lamia
      pyModule: lamia.wui.views
    - name: na58
      pyModule: na58.wui.views
      config: !include assets/na58/wui.yaml
      # ...
    # ...
...
